apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          args:
          - "/cloud_sql_proxy"
          - "--instances=$(PROJECT_ID):$(REGION):$(INSTANCE_NAME)=tcp:5432"
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/cloudsql/key.json
          envFrom:
            - secretRef:
                name: cloud-sql-env
          volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 350m
        - name: blog-backend
          image: unaldenizzz/blog-backend
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: blog-backend-env
          volumeMounts:
            - mountPath: /etc/gcs
              name: gcs-key
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 550m
      volumes:
        - name: gcs-key
          secret:
            secretName: gcs-credentials
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloud-sql-key
---
apiVersion: v1
kind: Service
metadata:
  name: blog-backend
spec:
  selector:
    app: blog-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
