apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: unaldenizzz/blog-frontend
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: blog-frontend-env

---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
spec:
  selector:
    app: blog-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
